version: "3"
services:
  web:
    container_name: morphicpro_elixir
    build: .
    environment:
      - DB_HOST=db
    env_file:
      - .env
    command: mix phx.server
    volumes:
      - $PWD:/app
      - ~/.aws:/root/.aws:ro
    ports:
      - "127.0.0.1:4001:4001"
    depends_on:
      - db
  db:
    image: "postgres:10"
    environment:
      POSTGRES_DB: "morphic_pro_dev"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    container_name: "morphicpro_postgres"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  # object_storage:
  #   image: "minio/minio"
  #   environment:
  #     MINIO_ACCESS_KEY: ""
  #     MINIO_SECRET_KEY: ""
  #   container_name: "morphicpro_minio"
  #   volumes:
  #     - object_storage:/data
  #   ports:
  #     - "127.0.0.1:9000:9000"
volumes:
  data:
    driver: local
  # object_storage:
  #   driver: local
  deps:
  _build:
  test:
